# Site settings
title: Elm Examples Blog
email: zkessin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This a blog to share examples of useful code for and around elm, Feel free to send in new posts as a pull request on github, I will merge liberally

baseurl: "/elm-examples-blog/" # the subpath of your site, e.g. /blog/
url: "http://zkessin.github.io" # the base hostname & protocol for your site
twitter_username: zkessin
github_username:  zkessin

# Build settings
markdown: kramdown
